version: "3.7"

services:
  transfair:
    container_name: transfair
    image: samply/transfair
    environment:
      RESOURCEFILTER: ${RESOURCE_FILTER}
      SOURCEFHIRSERVER: ${SOURCE_FHIR_SERVER}
      TARGETFHIRSERVER: ${TARGET_FHIR_SERVER}
      STARTRESOURCE: ${START_RESOURCE}
      SAVETOFILESYSTEM: ${SAVE_TO_FILESYSTEM}
    ports:
      - "8070:8070"
