version: "3.7"

services:
  transfair:
    container_name: transfair
    image: samply/transfair
    environment:
      TF_RESOURCES_FILTER: ${RESOURCE_FILTER}
      TF_SERVER_SOURCE_ADDRESS: ${SOURCE_FHIR_SERVER}
      TF_SERVER_TARGET_ADDRESS: ${TARGET_FHIR_SERVER}
      TF_RESOURCES_START: ${START_RESOURCE}
      TF_FHIR_FILESYSTEM: ${SAVE_TO_FILESYSTEM}
    ports:
      - "8070:8070"
