version: "3.7"

services:
  transfair:
    container_name: transfair
    image: samply/transfair
    environment:
      CSV_FILE: ""
      SOURCE_FORMAT: "bbmri.de"
      SOURCE_LOAD_FHIR: "true"
      SOURCE_FHIR_SERVER: "http://host.docker.internal:8080/fhir"
      SOURCE_LOAD_FILES: "false"
      TARGET_FORMAT: "bbmri.de"
      TARGET_POST_FHIR: "true"
      TARGET_FHIR_SERVER: "http://host.docker.internal:8083/fhir"
      TARGET_SAVE_FILES: "false"
    ports:
      - "8070:8070"
