server:
  port : 8070
logging:
  level:
    org:
      springframework: INFO

tf:
  profile: "none"
  resources:
    filter: ""
    start: ""
  id:
    patient:
      whitelist: ""
      blacklist: ""
  fhir:
    server:
      source:
        address: ""
        username: ""
        password: ""
      target:
        address: ""
        username: ""
        password: ""
    filesystem: "false"
  pseudo:
    csv: ""


