server:
  port : 8070
logging:
  level:
    org:
      springframework: DEBUG

app:
  source:
    format: "bbmri.de"
    loadFromFhirServer: true
    fhirserver: "http://localhost:8080/fhir"
    loadFromFileSystem: false
  target:
    format: "mii"
    saveToFhirServer: false
    fhirServer: "http://localhost:8081/fhir"
    saveToFileSystem: true
