server:
  port : 8070
logging:
  level:
    org:
      springframework: DEBUG


RESOURCEFILTER: ""
SOURCEFHIRSEVER: ""
TARGETFHIRSERVER: ""
MIIFHIRSERVER: ""
BBMRIFHIRSERVER: ""
STARTRESOURCE: ""
SAVETOFILESYSTEM: "false"
PSEUDOCSVFILE: ""

