server:
  port : 8070
logging:
  level:
    org:
      springframework: DEBUG

TF:

RESOURCEFILTER: ""
SOURCEFHIRSERVER: ""
TARGETFHIRSERVER: ""
STARTRESOURCE: ""
SAVETOFILESYSTEM: "false"
PSEUDOCSVFILE: ""

