server:
  port : 8070
logging:
  level:
    org:
      springframework: DEBUG

app:
  csvmapping:
    filepath: ${CSV_FILE}
  source:
    format: ${SOURCE_FORMAT}
    loadFromFhirServer: ${SOURCE_LOAD_FHIR}
    fhirserver: ${SOURCE_FHIR_SERVER}
    loadFromFileSystem: ${SOURCE_LOAD_FILES}
    resourceFilter: ${RESOURCE_FILTER}
    startResource: ${START_RESOURCE}
  target:
    format: ${TARGET_FORMAT}
    saveToFhirServer: ${TARGET_POST_FHIR}
    fhirServer: ${TARGET_FHIR_SERVER}
    saveToFileSystem: ${TARGET_SAVE_FILES}
  mapper:
    setting: ""
  csv:
    path: ""
