version: "3.7"

services:
  source_blaze:
      container_name: source-blaze
      image: samply/blaze:develop
      environment:
        BASE_URL: "http://host.docker.internal:8082"
      ports:
        - "8082:8080"

  target_blaze:
    container_name: target-blaze
    image: samply/blaze:develop
    environment:
      BASE_URL: "http://host.docker.internal:8083"
    ports:
      - "8083:8080"